import { useState, useEffect, useCallback } from "react";
import { useSearchParams } from "react-router-dom";
import { transactions as txApi, accounts as accountsApi, categories as catsApi, ai as aiApi } from "../api/client";
import GlassCard from "../components/GlassCard";
import { format } from "date-fns";

const fmt = (n) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(n);

const emptyForm = {
  accountId: "", toAccountId: "", categoryId: "",
  amount: "", description: "",
  date: format(new Date(), "yyyy-MM-dd"),
  type: "EXPENSE", notes: "",
};

const fieldStyle = { padding: "10px 14px", width: "100%", boxSizing: "border-box", display: "block" };
const labelStyle = { fontSize: 12, color: "rgba(255,255,255,0.5)", fontWeight: 500, display: "block", marginBottom: 16 };

// ── AI suggestions ───────────────────────────────────────────────────────────
// A small local model is good at tidying merchant names but only roughly right
// about categories, and it does occasionally invent a word. So every suggestion
// is shown next to the original and nothing is written until it is confirmed.
function AiReviewModal({ ids, categories, onClose, onApplied }) {
  const [state, setState] = useState({ phase: "loading" });
  const [rows, setRows] = useState([]);
  const [applying, setApplying] = useState(false);

  useEffect(() => {
    let cancelled = false;
    aiApi.suggest(ids)
      .then((r) => {
        if (cancelled) return;
        setRows(r.suggestions.map((s) => ({ ...s, keepName: true, keepCategory: !!s.categoryId })));
        setState({ phase: "review", failed: r.failed, model: r.model });
      })
      .catch((e) => {
        if (!cancelled) setState({ phase: "error", error: e.response?.data?.error || e.message });
      });
    return () => { cancelled = true; };
  }, []);

  const toggle = (id, field) =>
    setRows((rs) => rs.map((r) => (r.id === id ? { ...r, [field]: !r[field] } : r)));

  const setCategory = (id, categoryId) =>
    setRows((rs) => rs.map((r) => (r.id === id
      ? { ...r, categoryId: categoryId || null, keepCategory: !!categoryId }
      : r)));

  const setName = (id, description) =>
    setRows((rs) => rs.map((r) => (r.id === id ? { ...r, description } : r)));

  const changes = rows
    .map((r) => ({
      id: r.id,
      description: r.keepName && r.description !== r.current.description ? r.description : undefined,
      categoryId: r.keepCategory && r.categoryId ? r.categoryId : undefined,
    }))
    .filter((c) => c.description || c.categoryId);

  const apply = async () => {
    setApplying(true);
    try {
      const r = await aiApi.apply(changes);
      onApplied(`${r.updated} transaction${r.updated === 1 ? "" : "s"} updated`);
    } catch (e) {
      setState({ phase: "error", error: e.response?.data?.error || e.message });
      setApplying(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="glass-strong" style={{ width: 940, maxWidth: "96vw", maxHeight: "90vh", padding: 28, display: "flex", flexDirection: "column" }}>
        <h2 style={{ margin: 0, fontSize: 18 }}>Suggested categories and names</h2>
        <p style={{ margin: "4px 0 0", fontSize: 13, color: "rgba(255,255,255,0.45)", lineHeight: 1.6 }}>
          Generated by your own Ollama — nothing left this machine. Check them before applying:
          small models get most names right but are only roughly right about categories, and can
          occasionally invent a word.
        </p>

        {state.phase === "loading" && (
          <div style={{ padding: "40px 0", textAlign: "center", color: "rgba(255,255,255,0.4)", fontSize: 14 }}>
            Asking the model about {ids.length} transaction{ids.length === 1 ? "" : "s"}…
            <div style={{ fontSize: 12, marginTop: 6, color: "rgba(255,255,255,0.25)" }}>
              Roughly half a second each, so this can take a while for a large selection.
            </div>
          </div>
        )}

        {state.phase === "error" && (
          <div style={{ marginTop: 18, padding: "14px 16px", borderRadius: 10, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(248,113,113,0.35)", fontSize: 13, color: "#f87171", lineHeight: 1.6 }}>
            {state.error}
          </div>
        )}

        {state.phase === "review" && (
          <>
            {state.failed > 0 && (
              <div style={{ marginTop: 12, fontSize: 13, color: "#fbbf24" }}>
                The model did not answer for {state.failed} transaction{state.failed === 1 ? "" : "s"}; those are left alone.
              </div>
            )}

            <div style={{ flex: 1, overflowY: "auto", marginTop: 14, minHeight: 120 }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
                    {["", "Original", "Suggested name", "", "Category"].map((h, i) => (
                      <th key={i} style={{ padding: "8px 10px", textAlign: "left", color: "rgba(255,255,255,0.4)", fontWeight: 600, whiteSpace: "nowrap" }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => (
                    <tr key={r.id} style={{ borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                      <td style={{ padding: "8px 10px" }}>
                        <input
                          type="checkbox"
                          checked={r.keepName}
                          onChange={() => toggle(r.id, "keepName")}
                          title="Use the suggested name"
                          style={{ cursor: "pointer" }}
                        />
                      </td>
                      <td style={{ padding: "8px 10px", color: "rgba(255,255,255,0.4)", maxWidth: 240, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {r.current.description}
                      </td>
                      <td style={{ padding: "8px 10px" }}>
                        <input
                          className="glass-input"
                          style={{ padding: "5px 9px", width: "100%", fontSize: 13, opacity: r.keepName ? 1 : 0.4 }}
                          value={r.description}
                          onChange={(e) => setName(r.id, e.target.value)}
                          disabled={!r.keepName}
                        />
                      </td>
                      <td style={{ padding: "8px 10px" }}>
                        <input
                          type="checkbox"
                          checked={r.keepCategory}
                          onChange={() => toggle(r.id, "keepCategory")}
                          title="Use the suggested category"
                          disabled={!r.categoryId}
                          style={{ cursor: r.categoryId ? "pointer" : "not-allowed" }}
                        />
                      </td>
                      <td style={{ padding: "8px 10px" }}>
                        <select
                          className="glass-input"
                          style={{ padding: "5px 9px", fontSize: 13, minWidth: 150, opacity: r.keepCategory ? 1 : 0.4 }}
                          value={r.categoryId || ""}
                          onChange={(e) => setCategory(r.id, e.target.value)}
                        >
                          <option value="">— none —</option>
                          {categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
                        </select>
                        {r.rejectedCategory && (
                          <div style={{ fontSize: 11, color: "#fbbf24", marginTop: 2 }}>
                            suggested "{r.rejectedCategory}", which does not exist
                          </div>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginTop: 18, paddingTop: 16, borderTop: "1px solid rgba(255,255,255,0.08)" }}>
              <div style={{ fontSize: 13, color: "rgba(255,255,255,0.45)" }}>
                {changes.length} of {rows.length} will be changed
              </div>
              <div style={{ display: "flex", gap: 10 }}>
                <button className="glass-btn glass-btn-ghost" style={{ padding: "9px 18px" }} onClick={onClose}>Cancel</button>
                <button
                  className="glass-btn glass-btn-primary"
                  style={{ padding: "9px 20px", opacity: (!changes.length || applying) ? 0.5 : 1 }}
                  onClick={apply}
                  disabled={!changes.length || applying}
                >
                  {applying ? "Applying…" : `Apply ${changes.length}`}
                </button>
              </div>
            </div>
          </>
        )}

        {state.phase !== "review" && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 18 }}>
            <button className="glass-btn glass-btn-ghost" style={{ padding: "9px 18px" }} onClick={onClose}>Close</button>
          </div>
        )}
      </div>
    </div>
  );
}

export default function Transactions() {
  const [data, setData] = useState({ transactions: [], total: 0 });
  const [accounts, setAccounts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [modal, setModal] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [editing, setEditing] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");
  const [selected, setSelected] = useState([]);
  const [bulkBusy, setBulkBusy] = useState(false);
  const [bulkMsg, setBulkMsg] = useState(null);
  const [aiFor, setAiFor] = useState(null);
  const [searchParams] = useSearchParams();
  const [filters, setFilters] = useState({ search: "", accountId: searchParams.get("accountId") || "", categoryId: "", type: "", page: 1 });

  const load = useCallback(() => {
    txApi.list({ ...filters, limit: 50 }).then(setData);
  }, [filters]);

  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    accountsApi.list().then(setAccounts);
    catsApi.list().then(setCategories);
  }, []);

  const open = (item = null) => {
    setEditing(item?.id || null);
    setSaveError("");
    setForm(item ? {
      accountId: item.accountId,
      toAccountId: item.toAccountId || "",
      categoryId: item.categoryId || "",
      amount: item.amount,
      description: item.description,
      date: format(new Date(item.date), "yyyy-MM-dd"),
      type: item.type,
      notes: item.notes || "",
    } : { ...emptyForm, accountId: accounts[0]?.id || "" });
    setModal(true);
  };

  const save = async () => {
    if (!form.description.trim()) { setSaveError("Description is required"); return; }
    if (!form.amount || Number(form.amount) <= 0) { setSaveError("Enter a valid amount"); return; }
    if (!form.accountId) { setSaveError("Select an account"); return; }
    if (form.type === "TRANSFER" && !form.toAccountId) { setSaveError("Select a destination account"); return; }
    if (form.type === "TRANSFER" && form.toAccountId === form.accountId) { setSaveError("From and To accounts must be different"); return; }

    setSaveError("");
    setSaving(true);
    try {
      const payload = { ...form, amount: Number(form.amount), categoryId: form.categoryId || null };
      if (editing) await txApi.update(editing, payload);
      else await txApi.create(payload);
      setModal(false);
      load();
    } catch (err) {
      setSaveError(err.response?.data?.error || err.message || "Failed to save");
    } finally {
      setSaving(false);
    }
  };

  const remove = async (id) => {
    if (!confirm("Delete this transaction?")) return;
    await txApi.remove(id);
    load();
  };

  // ── Bulk selection ────────────────────────────────────────────
  // Selection is cleared whenever the visible rows change, so a hidden
  // selection can never be acted on by mistake.
  useEffect(() => { setSelected([]); setBulkMsg(null); }, [data.transactions]);

  const visibleIds = data.transactions.map((t) => t.id);
  const allSelected = visibleIds.length > 0 && visibleIds.every((id) => selected.includes(id));
  const toggleRow = (id) =>
    setSelected((s) => (s.includes(id) ? s.filter((x) => x !== id) : [...s, id]));
  const toggleAll = () => setSelected(allSelected ? [] : visibleIds);

  const runBulk = async (fn, describe) => {
    setBulkBusy(true);
    setBulkMsg(null);
    try {
      const res = await fn();
      setBulkMsg({ text: describe(res) });
      setSelected([]);
      load();
      accountsApi.list().then(setAccounts); // balances changed
    } catch (err) {
      setBulkMsg({ error: true, text: err.response?.data?.error || err.message });
    } finally {
      setBulkBusy(false);
    }
  };

  const bulkDelete = () => {
    if (!confirm(`Delete ${selected.length} transaction${selected.length === 1 ? "" : "s"}? Account balances are corrected. This cannot be undone.`)) return;
    runBulk(
      () => txApi.bulkRemove(selected),
      (r) => `${r.deleted} transaction${r.deleted === 1 ? "" : "s"} deleted`
    );
  };

  const bulkCategory = (categoryId) =>
    runBulk(
      () => txApi.bulkUpdate(selected, { categoryId: categoryId || null }),
      (r) => categoryId
        ? `${r.updated} transaction${r.updated === 1 ? "" : "s"} recategorized`
        : `Category cleared on ${r.updated} transaction${r.updated === 1 ? "" : "s"}`
    );

  const bulkType = (type) =>
    runBulk(
      () => txApi.bulkUpdate(selected, { type }),
      (r) => `${r.updated} changed to ${type.toLowerCase()}`
        + (r.skippedTransfers ? ` — ${r.skippedTransfers} transfer${r.skippedTransfers === 1 ? "" : "s"} left unchanged` : "")
    );

  const allCategories = categories.flatMap((c) => [c, ...(c.children || [])]);
  const isTransfer = form.type === "TRANSFER";

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <h1 style={{ fontSize: 26, fontWeight: 700, margin: 0 }}>Transactions</h1>
          <p style={{ color: "rgba(255,255,255,0.45)", margin: "4px 0 0", fontSize: 14 }}>{data.total} transactions</p>
        </div>
        <button className="glass-btn glass-btn-primary" style={{ padding: "10px 20px" }} onClick={() => open()}>+ Add</button>
      </div>

      {/* Filters */}
      <GlassCard style={{ padding: "16px 20px" }}>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <input className="glass-input" style={{ padding: "8px 12px", flex: "1 1 180px" }} placeholder="Search…" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value, page: 1 })} />
          <select className="glass-input" style={{ padding: "8px 12px" }} value={filters.accountId} onChange={(e) => setFilters({ ...filters, accountId: e.target.value, page: 1 })}>
            <option value="">All accounts</option>
            {accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
          </select>
          <select className="glass-input" style={{ padding: "8px 12px" }} value={filters.type} onChange={(e) => setFilters({ ...filters, type: e.target.value, page: 1 })}>
            <option value="">All types</option>
            <option value="INCOME">Income</option>
            <option value="EXPENSE">Expense</option>
            <option value="TRANSFER">Transfer</option>
          </select>
          <select className="glass-input" style={{ padding: "8px 12px" }} value={filters.categoryId} onChange={(e) => setFilters({ ...filters, categoryId: e.target.value, page: 1 })}>
            <option value="">All categories</option>
            {allCategories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
        </div>
      </GlassCard>

      {/* Bulk action bar */}
      {(selected.length > 0 || bulkMsg) && (
        <GlassCard style={{ padding: "12px 16px" }}>
          {bulkMsg && (
            <div style={{ fontSize: 13, marginBottom: selected.length ? 10 : 0, color: bulkMsg.error ? "#f87171" : "#34d399" }}>
              {bulkMsg.error ? "" : "✓ "}{bulkMsg.text}
            </div>
          )}
          {selected.length > 0 && (
            <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
              <span style={{ fontSize: 14, fontWeight: 600, whiteSpace: "nowrap" }}>
                {selected.length} selected
              </span>
              <button className="glass-btn glass-btn-ghost" style={{ padding: "6px 12px", fontSize: 13 }} onClick={() => setSelected([])} disabled={bulkBusy}>
                Clear
              </button>

              <span style={{ width: 1, height: 22, background: "rgba(255,255,255,0.1)" }} />

              <select
                className="glass-input"
                style={{ padding: "6px 10px", fontSize: 13 }}
                value=""
                disabled={bulkBusy}
                onChange={(e) => { if (e.target.value !== "") bulkCategory(e.target.value === "__none__" ? "" : e.target.value); }}
              >
                <option value="">Set category…</option>
                <option value="__none__">— No category —</option>
                {allCategories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>

              <select
                className="glass-input"
                style={{ padding: "6px 10px", fontSize: 13 }}
                value=""
                disabled={bulkBusy}
                onChange={(e) => { if (e.target.value) bulkType(e.target.value); }}
              >
                <option value="">Set type…</option>
                <option value="EXPENSE">Expense</option>
                <option value="INCOME">Income</option>
              </select>

              <button
                className="glass-btn glass-btn-ghost"
                style={{ padding: "6px 14px", fontSize: 13 }}
                onClick={() => setAiFor(selected)}
                disabled={bulkBusy}
                title="Suggest categories and cleaner names using your local Ollama"
              >
                ✨ Suggest
              </button>

              <button
                className="glass-btn glass-btn-danger"
                style={{ padding: "6px 14px", fontSize: 13, marginLeft: "auto" }}
                onClick={bulkDelete}
                disabled={bulkBusy}
              >
                {bulkBusy ? "Working…" : `Delete ${selected.length}`}
              </button>
            </div>
          )}
        </GlassCard>
      )}

      {aiFor && (
        <AiReviewModal
          ids={aiFor}
          categories={allCategories}
          onClose={() => setAiFor(null)}
          onApplied={(text) => { setAiFor(null); setBulkMsg({ text }); setSelected([]); load(); }}
        />
      )}

      {/* Table */}
      <GlassCard style={{ padding: 0, overflow: "hidden" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
              <th style={{ padding: "14px 8px 14px 16px", width: 32 }}>
                <input
                  type="checkbox"
                  checked={allSelected}
                  onChange={toggleAll}
                  title={allSelected ? "Deselect all" : "Select all on this page"}
                  style={{ cursor: "pointer" }}
                />
              </th>
              {["Date", "Description", "Account", "Category", "Type", "Amount", ""].map((h) => (
                <th key={h} style={{ padding: "14px 16px", textAlign: h === "Amount" ? "right" : "left", fontSize: 12, color: "rgba(255,255,255,0.4)", fontWeight: 600, whiteSpace: "nowrap" }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.transactions.map((t) => (
              <tr
                key={t.id}
                style={{
                  borderBottom: "1px solid rgba(255,255,255,0.04)",
                  background: selected.includes(t.id) ? "rgba(99,102,241,0.12)" : undefined,
                }}
              >
                <td style={{ padding: "12px 8px 12px 16px" }}>
                  <input
                    type="checkbox"
                    checked={selected.includes(t.id)}
                    onChange={() => toggleRow(t.id)}
                    style={{ cursor: "pointer" }}
                  />
                </td>
                <td style={{ padding: "12px 16px", fontSize: 13, color: "rgba(255,255,255,0.5)", whiteSpace: "nowrap" }}>{format(new Date(t.date), "dd MMM yyyy")}</td>
                <td style={{ padding: "12px 16px", fontSize: 14, fontWeight: 500, maxWidth: 200, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{t.description}</td>
                <td style={{ padding: "12px 16px", fontSize: 13, color: "rgba(255,255,255,0.5)" }}>
                  {t.type === "TRANSFER" && t.toAccount
                    ? <span>{t.account?.name} <span style={{ color: "rgba(255,255,255,0.3)" }}>→</span> {t.toAccount.name}</span>
                    : t.account?.name}
                </td>
                <td style={{ padding: "12px 16px" }}>
                  {t.category && (
                    <span style={{ background: `${t.category.color}22`, color: t.category.color, border: `1px solid ${t.category.color}44`, padding: "2px 10px", borderRadius: 999, fontSize: 12, fontWeight: 500 }}>
                      {t.category.name}
                    </span>
                  )}
                </td>
                <td style={{ padding: "12px 16px" }}>
                  <span className={`badge badge-${t.type.toLowerCase()}`}>{t.type}</span>
                </td>
                <td style={{ padding: "12px 16px", textAlign: "right", fontWeight: 700, fontSize: 15 }} className={t.type === "INCOME" ? "amount-income" : t.type === "EXPENSE" ? "amount-expense" : "amount-neutral"}>
                  {t.type === "EXPENSE" ? "-" : t.type === "INCOME" ? "+" : ""}{fmt(Number(t.amount))}
                </td>
                <td style={{ padding: "12px 16px", whiteSpace: "nowrap" }}>
                  <button className="glass-btn glass-btn-ghost" style={{ padding: "4px 10px", fontSize: 12, marginRight: 6 }} onClick={() => open(t)}>Edit</button>
                  <button className="glass-btn glass-btn-danger" style={{ padding: "4px 10px", fontSize: 12 }} onClick={() => remove(t.id)}>Del</button>
                </td>
              </tr>
            ))}
            {data.transactions.length === 0 && (
              <tr><td colSpan={8} style={{ padding: "60px 16px", textAlign: "center", color: "rgba(255,255,255,0.25)", fontSize: 14 }}>No transactions found</td></tr>
            )}
          </tbody>
        </table>
      </GlassCard>

      {/* Pagination */}
      {data.total > 50 && (
        <div style={{ display: "flex", gap: 8, justifyContent: "center" }}>
          <button className="glass-btn glass-btn-ghost" style={{ padding: "8px 16px" }} disabled={filters.page === 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>← Prev</button>
          <span style={{ padding: "8px 16px", color: "rgba(255,255,255,0.5)", fontSize: 13 }}>Page {filters.page}</span>
          <button className="glass-btn glass-btn-ghost" style={{ padding: "8px 16px" }} disabled={filters.page * 50 >= data.total} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next →</button>
        </div>
      )}

      {/* Modal */}
      {modal && (
        <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && setModal(false)}>
          <div className="glass-strong" style={{ width: 480, padding: "32px 36px", maxWidth: "95vw", borderRadius: 20 }}>
            <h2 style={{ margin: "0 0 24px", fontSize: 18, fontWeight: 700 }}>{editing ? "Edit" : "Add"} Transaction</h2>

            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {/* Type selector */}
              <div style={{ display: "flex", gap: 8 }}>
                {["EXPENSE", "INCOME", "TRANSFER"].map((t) => (
                  <button key={t} onClick={() => setForm({ ...form, type: t, toAccountId: "" })}
                    style={{
                      flex: 1, padding: "9px", borderRadius: 8, border: "none", cursor: "pointer", fontWeight: 600, fontSize: 13,
                      background: form.type === t
                        ? t === "INCOME" ? "rgba(52,211,153,0.25)" : t === "EXPENSE" ? "rgba(248,113,113,0.25)" : "rgba(148,163,184,0.25)"
                        : "rgba(255,255,255,0.05)",
                      color: form.type === t
                        ? t === "INCOME" ? "#34d399" : t === "EXPENSE" ? "#f87171" : "#94a3b8"
                        : "rgba(255,255,255,0.4)",
                      outline: form.type === t ? "1px solid currentColor" : "1px solid transparent",
                    }}>
                    {t === "EXPENSE" ? "Expense" : t === "INCOME" ? "Income" : "Transfer"}
                  </button>
                ))}
              </div>

              <label style={labelStyle}>
                Description
                <input className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} placeholder="What was this for?" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} autoFocus />
              </label>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                <label style={labelStyle}>
                  Amount
                  <input className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} type="number" min="0" step="0.01" placeholder="0.00" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} />
                </label>
                <label style={labelStyle}>
                  Date
                  <input className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
                </label>
              </div>

              {isTransfer ? (
                <div style={{ display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 8, alignItems: "end" }}>
                  <label style={labelStyle}>
                    From account
                    <select className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} value={form.accountId} onChange={(e) => setForm({ ...form, accountId: e.target.value })}>
                      <option value="">Select…</option>
                      {accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
                    </select>
                  </label>
                  <div style={{ paddingBottom: 12, color: "rgba(255,255,255,0.3)", fontSize: 18, textAlign: "center" }}>→</div>
                  <label style={labelStyle}>
                    To account
                    <select className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} value={form.toAccountId} onChange={(e) => setForm({ ...form, toAccountId: e.target.value })}>
                      <option value="">Select…</option>
                      {accounts.filter((a) => a.id !== form.accountId).map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
                    </select>
                  </label>
                </div>
              ) : (
                <label style={labelStyle}>
                  Account
                  <select className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} value={form.accountId} onChange={(e) => setForm({ ...form, accountId: e.target.value })}>
                    <option value="">Select account…</option>
                    {accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
                  </select>
                </label>
              )}

              {!isTransfer && (
                <label style={labelStyle}>
                  Category
                  <select className="glass-input" style={{ ...fieldStyle, marginTop: 6 }} value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}>
                    <option value="">No category</option>
                    {allCategories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
                  </select>
                </label>
              )}

              <label style={labelStyle}>
                Notes <span style={{ color: "rgba(255,255,255,0.3)", fontWeight: 400 }}>(optional)</span>
                <textarea className="glass-input" style={{ ...fieldStyle, marginTop: 6, resize: "vertical", minHeight: 56 }} placeholder="Any extra details…" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} />
              </label>
            </div>

            {saveError && (
              <div style={{ marginTop: 16, padding: "10px 14px", borderRadius: 8, background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", color: "#fca5a5", fontSize: 13 }}>
                {saveError}
              </div>
            )}

            <div style={{ display: "flex", gap: 10, marginTop: 20, justifyContent: "flex-end" }}>
              <button className="glass-btn glass-btn-ghost" style={{ padding: "10px 22px" }} onClick={() => setModal(false)}>Cancel</button>
              <button className="glass-btn glass-btn-primary" style={{ padding: "10px 22px", opacity: saving ? 0.7 : 1 }} onClick={save} disabled={saving}>
                {saving ? "Saving…" : "Save"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
